---
- meta: end_play 
  when:
    - ka_sentinel_enabled == "no"

- name: Install keepalived
  yum:
#    name: "{{ item }}"
    name: ['keepalived']
    state: present
#  with_items:
#     - keepalived

- name: Mkdir /etc/keepalived/scripts
  file: path=/etc/keepalived/scripts mode=0755 state=directory recurse=yes

- name: Configure keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Copy keepalived
  copy: src=track_master.sh dest=/etc/keepalived/scripts/track_master.sh mode=0755

- name: Modify track_master.sh
  shell: sed -i "s/REDIS_CLI=.*$/REDIS_CLI=\"redis-cli -a {{ redis_password }}\"/" /etc/keepalived/scripts/track_master.sh
  ignore_errors: yes
  when:
    - '{{ redis_password != "" }}'

- name: Disble selinux
  shell: |
    sed -i '/^SELINUX=/s/=.*$/=disabled/' /etc/selinux/config
    setenforce 0
  ignore_errors: yes

- name: Start keepalived
  service: name=keepalived state=restarted enabled=yes

