---
- name: 安装Java8
  yum: name={{ item }} state=present
  with_items:
     - yum-utils
     - java-1.8.0

- name: 将tomcat8解压缩到安装目录下
  unarchive:
    src: "{{ app_name }}.tar.gz"
    dest: "{{ install_path }}"

- name: 注册tomcat环境变量
  lineinfile:
    dest: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - "export CATALINA_HOME=/usr/local/apache-tomcat-8.5.38/"
    - "export PATH=$CATALINA_HOME/bin:$PATH"

- name: 检测tomcat安装目录是否存在
  stat: path={{ tomcat_home }}
  register: check_tomcat_result
  failed_when: not check_tomcat_result.stat.exists

- name: 替换examples首页
  template: src=index.html  dest="{{ tomcat_home }}/webapps/examples/index.html"

- name: 启动tomcat
  shell: nohup "{{ tomcat_home }}/bin/startup.sh" &

- name: 启用防火墙
  service: name=firewalld state=started enabled=yes

- name: 开启8080端口（临时）
  shell: firewall-cmd --zone=public --add-port=8080/tcp

- name: 等待8080端口启动
  wait_for:
    port: 8080
    state: started

- name: 配置tomcat开机自启动
  lineinfile:
    dest: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - "{{ tomcat_home }}/bin/startup.sh &"

